{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ .Values.ingress.tls.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - thearc
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{ end }}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
{{- end -}}
